config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: :show
  resources :clients, only: :show

  namespace :admin do
    resources :reports
    resources :log_entries do
      get :duplicate
      collection do
        get :current, action: :index, scope: :current
        get :archived, action: :index, scope: :archived
      end
    end
    resources :repositories do
      resources :log_entries do
        collection do
          get :current, action: :index, scope: :current
          get :archived, action: :index, scope: :archived
        end

      end
    end
    root to: 'repositories#index'
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :client
  has_many :log_entries

  validates_presence_of :name

  def client_name
    client.name if client
  end

  def last_log_entry
    log_entries.order('completed_at').last
  end
end

app/controllers/admin/repositories_controller.rb
module Admin
  class RepositoriesController < AdminController

    def index
      @repositories = Repository.all
    end

  end
end

app/views/admin/repositories/index.html.erb
<h2>
  Repositories
</h2>

<%- if @repositories.any? -%>
<table class="table">
  <thead>
    <tr>
      <th>Repository</th>
      <th>Client</th>
      <th>Last Entry</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.order('last_entry_at NULLS FIRST').each do |repository| %>
      <tr>
        <td><%= link_to repository.name, admin_repository_log_entries_path(repository) %></td>
        <td><%= repository.client_name %></td>
        <td><%= time_ago_or_nil repository.last_entry_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%- else -%>
  <p class="alert alert-info">No repositories found.</p>
<%- end -%>