config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: :show
  resources :clients, only: :show

  namespace :admin do
    resources :reports
    resources :log_entries do
      get :duplicate
      collection do
        get :current, action: :index, scope: :current
        get :archived, action: :index, scope: :archived
      end
    end
    resources :repositories do
      resources :log_entries do
        collection do
          get :current, action: :index, scope: :current
          get :archived, action: :index, scope: :archived
        end

      end
    end
    root to: 'repositories#index'
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :client
  belongs_to :repository

  has_many :log_entries

  validates_presence_of :report_date

  before_save :set_client_id
  before_save :generate_token

  def to_param
    token
  end

  def client_reports
    client.reports if client
  end

  def month
    report_date.beginning_of_month
  end

  def client_name
    client.name if client
  end

  def repository_name
    repository.name if repository
  end

  def gem_details
    log_entries.select(&:gems?).map(&:note).join("\n")
  end

  def exceptions
    log_entries.select(&:exception?)
  end

  def security_entries
    log_entries.select(&:security?)
  end

  def notes
    log_entries.select(&:note?)
  end

  def private_notes
    log_entries.select(&:private_note?)
  end

private

  def generate_token
    self.token ||= SecureRandom.uuid
  end

  def set_client_id
    self.client_id ||= repository.client_id
  end

end

app/controllers/admin/reports_controller.rb
module Admin
  class ReportsController < AdminController

    def index
      @reports = Report.all.includes(:repository, :client).order('report_date DESC')
    end

    def new
      @report = Report.new do |r|
        r.repository = repository
        r.report_date = params[:date] || default_date
        r.report_date = r.report_date.end_of_month
      end
      add_entries
    end

    def edit
      @report = Report.find_by_token(params[:id])
      @new_entry = LogEntry.new do |e|
        e.repository = @report.repository
        e.completed_at = @report.report_date
        e.report_id = @report.id
      end
    end

    def create
      @report = Report.new params[:report]
      add_entries
      @report.save
      respond_with @report
    end

  private

    def repository
      @repository ||= Repository.find params[:repository_id] if params[:repository_id]
    end

    def default_date
      Date.today - 1.month
    end

    def default_log_entries
      @report.repository.log_entries.unpublished.order(:completed_at)
    end

    def add_entries
      @report.log_entries = default_log_entries.where('completed_at <= ?', @report.report_date)
    end

  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def show
    @report = Report.find_by_token! params[:id]
  end

end

app/views/admin/reports/_form.html.erb
<%= bootstrap_form_for [:admin, report] do |f| %>
  <%= f.alert_message "Please fix the errors below." %>

  <%= f.hidden_field :repository_id %>
  <%= f.date_field :report_date %>

  <div class='form-group'>
    <%= f.primary 'Save' %>
  </div>

<%- end -%>

app/views/admin/reports/_log_entry_form.html.erb
<%= bootstrap_form_for [:admin, entry] do |f| %>

  <%= f.alert_message "Please fix the errors below." %>

  <%= f.hidden_field :report_id %>
  <%= f.hidden_field :repository_id %>

  <%= f.collection_select :entry_type, LogEntry::TYPES, :to_s, :humanize, prompt: 'Please select…' %>
  <%= f.date_field :completed_at %>
  <%= f.text_area :note %>

  <div class='form-group'>
    <%= f.primary 'Save' %>
  </div>

<%- end -%>

app/views/admin/reports/_private_notes.html.erb
<h4>Private Notes</h4>
<ul>
  <%- entries.each do |entry| %>
    <li>
      <%= entry.completed_at.to_date.iso8601 %>
      <%= entry.note %>
    </li>
  <% end %>
</ul>

app/views/admin/reports/edit.html.erb
<h2>
  <%= link_to 'Reports', admin_reports_path %>
  &rarr;
  <%= @report.repository_name %>
</h2>

<%= render 'form', report: @report %>
<%= render 'private_notes', entries: @report.private_notes if @report.private_notes.any? %>

<h2>Report</h2>
<%= render 'reports/report', report: @report %>
<h4>Add Entry</h4>
<%= render 'log_entry_form', entry: @new_entry %>

app/views/admin/reports/index.html.erb
<h2>
  Reports
</h2>

<ul class="nav nav-pills">
  <%- Client.all.each do |client| %>
    <li>
      <%= link_to client.name, client_path(id: client.token) if client.token %>
    </li>
  <% end %>
</ul>

<%- if @reports.present? -%>
<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Repository</th>
    </tr>
  </thead>

  <tbody>
    <%- @reports.group_by(&:month).each do |month, reports| -%>
      <tr class="active">
        <th colspan="99"><%= render_month month %></th>
      </tr>
      <% reports.each do |report| %>
        <tr>
          <td><%= report.client_name %></td>
          <td><%= report.repository_name %></td>
          <td>
            <%= link_to 'View', report_path(report), class: 'btn btn-default btn-xs pull-right' %>
            <%= link_to 'Edit', edit_admin_report_path(report), class: 'btn btn-default btn-xs pull-right' %>
          </td>
        </tr>
      <% end %>
    <%- end -%>
  </tbody>
</table>
<%- else -%>
  <p class="alert alert-info">No reports found.</p>
<%- end -%>

app/views/admin/reports/new.html.erb
<h2>
  <%= link_to 'Reports', admin_reports_path %>
  &rarr;
  <%= @report.repository_name %>
  &rarr;
  New
</h2>

<%= render 'form', report: @report %>
<%= render 'private_notes', entries: @report.private_notes if @report.private_notes.any? %>

<h2>Report Preview</h2>
<%= render 'reports/report', report: @report %>