config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: :show
  resources :clients, only: :show

  namespace :admin do
    resources :reports
    resources :log_entries do
      get :duplicate
      collection do
        get :current, action: :index, scope: :current
        get :archived, action: :index, scope: :archived
      end
    end
    resources :repositories do
      resources :log_entries do
        collection do
          get :current, action: :index, scope: :current
          get :archived, action: :index, scope: :archived
        end

      end
    end
    root to: 'repositories#index'
  end
end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  TYPES = %w[
    security
    gems
    exception
    note
    private_note
  ].freeze

  belongs_to :repository
  belongs_to :report

  scope :unpublished, -> { where report_id: nil }
  scope :published, -> { where 'report_id is not null' }

  store :data, {
    accessors: [
      :note,
    ],
    coder: JSON,
  }

  validates_presence_of :repository_id, :entry_type, :note

  before_save :default_completed_at
  after_create :update_repo_timestamp

  def client_name
    client.name if client
  end

  def repository_name
    repository.name if repository
  end

  def client
    repository.client if repository
  end

  def gems?
    entry_type == 'gems'
  end

  def exception?
    entry_type == 'exception'
  end

  def security?
    entry_type == 'security'
  end

  def note?
    entry_type == 'note'
  end

  def private_note?
    entry_type == 'private_note'
  end

private

  def default_completed_at
    self.completed_at ||= Time.current
  end

  def update_repo_timestamp
    return if repository.last_entry_at && repository.last_entry_at > completed_at
    repository.update_columns last_entry_at: completed_at
  end

end

app/controllers/admin/log_entries_controller.rb
module Admin
  class LogEntriesController < AdminController

    DEFAULT_SCOPE = :current

    helper_method :repository
    helper_method :entries_scope

    def index
      @entry_groups = scope.order('completed_at DESC').group_by {|e| e.completed_at.strftime "%a, %e %b"}
    end

    def new
      @entry = LogEntry.new
      @entry.repository = repository if repository
    end

    def edit
      @entry = LogEntry.find params[:id]
    end

    def duplicate
      @entry = LogEntry.find(params[:log_entry_id]).dup
      @entry.repository = nil
      render 'new'
    end

    def create
      @entry = LogEntry.create params[:log_entry]
      respond_with @entry, location: redirect_path
    end

    def update
      @entry = LogEntry.find params[:id]
      @entry.update_attributes params[:log_entry]
      respond_with @entry, location: redirect_path
    end

  private

    def repository
      @repository ||= Repository.find params[:repository_id] if params[:repository_id]
    end

    def redirect_path
      if params[:add]
        new_admin_repository_log_entry_path @entry.repository
      elsif @entry.report
        edit_admin_report_path(@entry.report)
      else
        admin_repository_log_entries_path @entry.repository
      end
    end

    def scope
      case entries_scope
      when :current then repository_scope.unpublished
      when :archived then repository_scope.published
      else
        repository_scope.none
      end
    end

    def repository_scope
      repository ? repository.log_entries : LogEntry
    end

    def entries_scope
      @entries_scope ||= params[:scope] || DEFAULT_SCOPE
    end

  end
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
  def scoped_submenu_item(name, scope)
    submenu_item name, { scope: scope }, entries_scope == scope
  end

  def maybe_edit_link(entry)
    return unless admin?
    content_tag :div, class: 'pull-right' do
      link_to 'Edit', polymorphic_url([:admin, entry], action: :edit), class: 'btn btn-default btn-xs'
    end
  end
end

app/views/admin/log_entries/_form.html.erb
<%= bootstrap_form_for [:admin, entry] do |f| %>

  <%= f.alert_message "Please fix the errors below." %>

  <%= f.collection_select :repository_id, Repository.all.order('client_id, name'), :id, :name, prompt: 'Please select…' %>
  <%= f.collection_select :entry_type, LogEntry::TYPES, :to_s, :humanize, prompt: 'Please select…' %>
  <%= f.text_area :note %>

  <div class='form-group'>
    <%= f.primary 'Save' %>
    <%= f.button 'Save & Add Another', name: 'add', value: true, class: 'btn btn-primary' %>
  </div>

<%- end -%>

app/views/admin/log_entries/_gem_versions.html.erb
<div id="gems">
  <h4>Gems upgraded</h4>

  <table class="table table-condensed table-responsive" style="width:auto">
    <thead>
      <tr>
        <th>Gem</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%- GemUpgrades.parse(@entry.note).each do |gem_name, upgrade| -%>
      <tr>
        <td><%= gem_name %></td>
        <td><%= upgrade[:from] %></td>
        <th>&rarr;</th>
        <td><%= upgrade[:to] %></td>
      </tr>
    <%- end -%>
    </tbody>
  </table>
</div>

app/views/admin/log_entries/edit.html.erb
<h2>
  <%= link_to 'Log Entries', admin_log_entries_path %>
  &rarr;
  Edit
</h2>

<%= render 'form', entry: @entry %>

<%= render 'reports/gem_versions', details: @entry.note if @entry.gems? %>

app/views/admin/log_entries/index.html.erb
<h2>
  <%= "#{repository.name} →" if repository %>
  Log Entries
  <%= link_to 'Add Entry', new_admin_log_entry_path(repository_id: repository), class: 'action' %>
  <%= link_to 'New Report', new_admin_report_path(repository_id: repository), class: 'action' if repository %>
</h2>

<ul class="nav nav-tabs" role="tablist" style="margin-bottom: 1em">
  <%= scoped_submenu_item 'Current', :current %>
  <%= scoped_submenu_item 'Archived', :archived %>
</ul>

<%- if @entry_groups.any? -%>
<table class="table">
  <thead>
    <tr>
      <th>Repository</th>
      <th>Type</th>
      <th>Note</th>
    </tr>
  </thead>

  <tbody>
    <%- @entry_groups.each do |group_name, entries| -%>
      <tr class="active">
        <th colspan="99"><%= group_name %></th>
      </tr>
      <% entries.each do |entry| %>
        <tr>
          <td><%= entry.repository_name %></td>
          <td><%= entry.entry_type.humanize %></td>
          <td>
            <%= parse_note entry %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_log_entry_path(entry), class: 'btn btn-default btn-xs pull-right' %>
            <%= link_to 'Duplicate', admin_log_entry_duplicate_path(entry), class: 'btn btn-default btn-xs pull-right' %>
          </td>
        </tr>
      <% end %>
    <%- end -%>
  </tbody>
</table>
<%- else -%>
  <p class="alert alert-info">No entries found.</p>
<%- end -%>

app/views/admin/log_entries/new.html.erb
<h2>
  <%= link_to 'Log Entries', admin_log_entries_path %>
  &rarr;
  New
</h2>

<%= render 'form', entry: @entry %>