config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: :show
  resources :clients, only: :show

  namespace :admin do
    resources :reports
    resources :log_entries do
      get :duplicate
      collection do
        get :current, action: :index, scope: :current
        get :archived, action: :index, scope: :archived
      end
    end
    resources :repositories do
      resources :log_entries do
        collection do
          get :current, action: :index, scope: :current
          get :archived, action: :index, scope: :archived
        end

      end
    end
    root to: 'repositories#index'
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "#{controller_name} #{action_name}".titleize + " | F1 SLA Report" %></title>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body>

    <%= navbar do %>
      <%= navbar_header brand: 'F1 SLA Report Manager', brand_link: '/' %>
      <%= navbar_collapse do %>
        <%= navbar_group do %>
          <%= navbar_item 'Repositories', admin_repositories_path %>
          <%= navbar_item 'Log Entries', admin_log_entries_path %>
          <%= navbar_item 'Reports', admin_reports_path %>
        <%- end -%>
      <%- end -%>
    <%- end -%>


    <div class="container">
      <%= yield %>
    </div>

    <%= yield :footer %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "#{controller_name} #{action_name}".titleize + " | F1 SLA Report" %></title>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%= yield :footer %>

    <%= javascript_include_tag "application" %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/reports.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "#{controller_name} #{action_name}".titleize + " | F1 SLA Report" %></title>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", media: "all" %>
  </head>
  <body class="report">
    <div class="container">
      <%= yield %>
    </div>

    <%= yield :footer %>

    <%= javascript_include_tag "application" %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>